// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Generated from statecharts/GuiSm.plantuml. Do not edit by hand.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum __attribute__ ((packed)) GuiSm_EventId
{
    GuiSm_EventId_ACTIVATE = 0
} GuiSm_EventId;

#define GuiSm_EventIdCount (1)

typedef enum __attribute__ ((packed)) GuiSm_StateId
{
    GuiSm_StateId_ROOT = 0,
    GuiSm_StateId_DIAGNOSTIC_FACE = 1,
    GuiSm_StateId_HOME_CONTEXT = 2
} GuiSm_StateId;

#define GuiSm_StateIdCount (3)

// Subtree meta data generation can be disabled in settings.
// Details: https://github.com/StateSmith/StateSmith/issues/538
#define GuiSm_ROOT_SubtreeEndId (2)  // State 'GuiSm' subtree extends from itself (id: 0) to state 'HOME_CONTEXT' (id: 2)
#define GuiSm_DIAGNOSTIC_FACE_SubtreeEndId (1)  // State 'DIAGNOSTIC_FACE' subtree extends from itself (id: 1) to state 'DIAGNOSTIC_FACE' (id: 1)
#define GuiSm_HOME_CONTEXT_SubtreeEndId (2)  // State 'HOME_CONTEXT' subtree extends from itself (id: 2) to state 'HOME_CONTEXT' (id: 2)


// Generated state machine
// forward declaration
typedef struct GuiSm GuiSm;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void GuiSm_ctor(GuiSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void GuiSm_start(GuiSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void GuiSm_dispatch_event(GuiSm* sm, GuiSm_EventId event_id);

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * GuiSm_state_id_to_string(GuiSm_StateId id);

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * GuiSm_event_id_to_string(GuiSm_EventId id);

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
GuiSm_StateId GuiSm_get_parent_id(GuiSm_StateId id);

// Generated state machine
struct GuiSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    GuiSm_StateId state_id;
};

