// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Generated from statecharts/GuiSm.plantuml. Do not edit by hand.

#include "GuiSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "watch/gui_state_actions.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(GuiSm* sm, GuiSm_StateId desired_state);

static void ROOT_enter(GuiSm* sm);

static void DIAGNOSTIC_FACE_enter(GuiSm* sm);

static void DIAGNOSTIC_FACE_exit(GuiSm* sm);

static void DIAGNOSTIC_FACE_activate(GuiSm* sm);

static void HOME_CONTEXT_enter(GuiSm* sm);

static void HOME_CONTEXT_exit(GuiSm* sm);

static void HOME_CONTEXT_activate(GuiSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void GuiSm_ctor(GuiSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void GuiSm_start(GuiSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(HOME_CONTEXT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `HOME_CONTEXT`.
            HOME_CONTEXT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void GuiSm_dispatch_event(GuiSm* sm, GuiSm_EventId event_id)
{
    // This state machine design only has a single event type so we can safely assume
    // that the dispatched event is `activate` without checking the `event_id` parameter.
    (void)event_id; // This line prevents an 'unused variable' compiler warning
    
    switch (sm->state_id)
    {
        // STATE: GuiSm
        case GuiSm_StateId_ROOT:
            // state and ancestors have no handler for `activate` event.
            break;
        
        // STATE: DIAGNOSTIC_FACE
        case GuiSm_StateId_DIAGNOSTIC_FACE:
            DIAGNOSTIC_FACE_activate(sm); 
            break;
        
        // STATE: HOME_CONTEXT
        case GuiSm_StateId_HOME_CONTEXT:
            HOME_CONTEXT_activate(sm); 
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(GuiSm* sm, GuiSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case GuiSm_StateId_DIAGNOSTIC_FACE: DIAGNOSTIC_FACE_exit(sm); break;
            
            case GuiSm_StateId_HOME_CONTEXT: HOME_CONTEXT_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(GuiSm* sm)
{
    sm->state_id = GuiSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state DIAGNOSTIC_FACE
////////////////////////////////////////////////////////////////////////////////

static void DIAGNOSTIC_FACE_enter(GuiSm* sm)
{
    sm->state_id = GuiSm_StateId_DIAGNOSTIC_FACE;
    
    // DIAGNOSTIC_FACE behavior
    // uml: enter / { watch_gui_show_diagnostic(); }
    {
        // Step 1: execute action `watch_gui_show_diagnostic();`
        watch_gui_show_diagnostic();
    } // end of behavior for DIAGNOSTIC_FACE
}

static void DIAGNOSTIC_FACE_exit(GuiSm* sm)
{
    sm->state_id = GuiSm_StateId_ROOT;
}

static void DIAGNOSTIC_FACE_activate(GuiSm* sm)
{
    // DIAGNOSTIC_FACE behavior
    // uml: ACTIVATE TransitionTo(HOME_CONTEXT)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        DIAGNOSTIC_FACE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME_CONTEXT`.
        HOME_CONTEXT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for DIAGNOSTIC_FACE
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state HOME_CONTEXT
////////////////////////////////////////////////////////////////////////////////

static void HOME_CONTEXT_enter(GuiSm* sm)
{
    sm->state_id = GuiSm_StateId_HOME_CONTEXT;
    
    // HOME_CONTEXT behavior
    // uml: enter / { watch_gui_show_home(); }
    {
        // Step 1: execute action `watch_gui_show_home();`
        watch_gui_show_home();
    } // end of behavior for HOME_CONTEXT
}

static void HOME_CONTEXT_exit(GuiSm* sm)
{
    sm->state_id = GuiSm_StateId_ROOT;
}

static void HOME_CONTEXT_activate(GuiSm* sm)
{
    // HOME_CONTEXT behavior
    // uml: ACTIVATE TransitionTo(DIAGNOSTIC_FACE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_CONTEXT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `DIAGNOSTIC_FACE`.
        DIAGNOSTIC_FACE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME_CONTEXT
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * GuiSm_state_id_to_string(GuiSm_StateId id)
{
    switch (id)
    {
        case GuiSm_StateId_ROOT: return "ROOT";
        case GuiSm_StateId_DIAGNOSTIC_FACE: return "DIAGNOSTIC_FACE";
        case GuiSm_StateId_HOME_CONTEXT: return "HOME_CONTEXT";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * GuiSm_event_id_to_string(GuiSm_EventId id)
{
    switch (id)
    {
        case GuiSm_EventId_ACTIVATE: return "ACTIVATE";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
GuiSm_StateId GuiSm_get_parent_id(GuiSm_StateId id)
{
    switch (id)
    {
        case GuiSm_StateId_ROOT: return GuiSm_StateId_ROOT;
        case GuiSm_StateId_DIAGNOSTIC_FACE: return GuiSm_StateId_ROOT;
        case GuiSm_StateId_HOME_CONTEXT: return GuiSm_StateId_ROOT;
        default: return GuiSm_StateId_ROOT;
    }
}
