$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$edge = "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"
if (-not (Test-Path -LiteralPath $edge)) {
    $edge = "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe"
}
if (-not (Test-Path -LiteralPath $edge)) {
    throw "Microsoft Edge is required to rasterize the supplied Roboto WOFF2 assets."
}

$profiles = @(
    [pscustomobject]@{ Name="MICRO";   Size=8;  TimeOnly=$false },
    [pscustomobject]@{ Name="CAPTION"; Size=10; TimeOnly=$false },
    [pscustomobject]@{ Name="BODY";    Size=12; TimeOnly=$false },
    [pscustomobject]@{ Name="ROW";     Size=16; TimeOnly=$false },
    [pscustomobject]@{ Name="TITLE";   Size=20; TimeOnly=$false },
    [pscustomobject]@{ Name="STATUS";  Size=23; TimeOnly=$false },
    [pscustomobject]@{ Name="DEVICE";  Size=39; TimeOnly=$false },
    [pscustomobject]@{ Name="TIME";    Size=64; TimeOnly=$true }
)

$codepoints = [System.Collections.Generic.List[int]]::new()
for ($cp = 0x20; $cp -le 0x7E; $cp++) { $codepoints.Add($cp) }
$codepoints.Add(0x00B0)
$codepoints.Add(0x0401)
for ($cp = 0x0410; $cp -le 0x044F; $cp++) { $codepoints.Add($cp) }
$codepoints.Add(0x0451)
$codepoints.Add(0x2212)
$timeCodepoints = @(
    [int][char]'0',[int][char]'1',[int][char]'2',[int][char]'3',
    [int][char]'4',[int][char]'5',[int][char]'6',[int][char]'7',
    [int][char]'8',[int][char]'9',[int][char]':'
)

$source = Join-Path $projectRoot "tools/strict-context-host/font-atlas.html"
$outputDir = Join-Path $projectRoot "build/strict-context-assets"
$atlasPath = Join-Path $outputDir "font-atlas.png"
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

& $edge --headless=new --disable-gpu --hide-scrollbars `
    --force-device-scale-factor=1 --window-size=1280,7040 `
    --run-all-compositor-stages-before-draw --virtual-time-budget=2000 `
    "--screenshot=$atlasPath" ([System.Uri]$source).AbsoluteUri | Out-Null
if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $atlasPath)) {
    throw "Roboto glyph atlas rendering failed."
}

Add-Type -AssemblyName System.Drawing
$atlas = [System.Drawing.Bitmap]::FromFile($atlasPath)
if ($atlas.Width -ne 1280 -or $atlas.Height -ne 7040) {
    throw "Roboto glyph atlas must be 1280x7040."
}

$header = @(
    "/* Generated from the supplied Apache-2.0 Roboto authoring assets. */",
    "#ifndef WATCH_STRICT_CONTEXT_TEXT_H",
    "#define WATCH_STRICT_CONTEXT_TEXT_H",
    "",
    "#include <stdbool.h>",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "#include <gno/gno.h>",
    "",
    "typedef enum {"
)
for ($index = 0; $index -lt $profiles.Count; $index++) {
    $comma = if ($index -lt ($profiles.Count - 1)) { "," } else { "" }
    $header += "    WATCH_STRICT_TEXT_$($profiles[$index].Name)$comma"
}
$header += @(
    "} watch_strict_text_style_t;",
    "",
    "void watch_strict_draw_text(gno_context_t *graphics, int x, int y,",
    "                            const char *text,",
    "                            watch_strict_text_style_t style,",
    "                            gno_color_t color);",
    "int watch_strict_text_width(const char *text,",
    "                            watch_strict_text_style_t style);",
    "uint8_t watch_strict_text_line_height(watch_strict_text_style_t style);",
    "",
    "bool watch_strict_rasterize_mask(uint8_t *bits, size_t bits_size,",
    "                                 uint16_t width, uint16_t height,",
    "                                 int x, int y, const char *text,",
    "                                 watch_strict_text_style_t style);",
    "bool watch_strict_rasterize_mask_add(uint8_t *bits, size_t bits_size,",
    "                                     uint16_t width, uint16_t height,",
    "                                     int x, int y, const char *text,",
    "                                     watch_strict_text_style_t style);",
    "",
    "#endif"
)

$sourceLines = @(
    "/* Generated by scripts/generate-strict-font.ps1. Do not edit. */",
    "#include `"watch/strict_context_text.h`"",
    "",
    "#include <stdbool.h>",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    "typedef struct {",
    "    uint32_t codepoint;",
    "    uint32_t bitmap_offset;",
    "    uint8_t width;",
    "    uint8_t height;",
    "    int8_t x_offset;",
    "    int8_t y_offset;",
    "    uint8_t advance;",
    "} strict_glyph_t;",
    "",
    "typedef struct {",
    "    const strict_glyph_t *glyphs;",
    "    const uint8_t *bitmap;",
    "    uint16_t glyph_count;",
    "    uint8_t line_height;",
    "} strict_font_t;",
    ""
)

$fontTableRows = [System.Collections.Generic.List[string]]::new()
$totalBytes = 0
for ($profileIndex = 0; $profileIndex -lt $profiles.Count; $profileIndex++) {
    $profile = $profiles[$profileIndex]
    $profileCodepoints = if ($profile.TimeOnly) { $timeCodepoints } else { $codepoints }
    $bitmapBytes = [System.Collections.Generic.List[byte]]::new()
    $glyphRows = [System.Collections.Generic.List[string]]::new()

    for ($glyphIndex = 0; $glyphIndex -lt $profileCodepoints.Count; $glyphIndex++) {
        $cp = $profileCodepoints[$glyphIndex]
        $cellX = ($glyphIndex % 16) * 80
        $cellY = ($profileIndex * 880) + ([math]::Floor($glyphIndex / 16) * 80)

        $advance = -1
        for ($x = 0; $x -lt 80; $x++) {
            $pixel = $atlas.GetPixel($cellX + $x, $cellY)
            if ($pixel.R -ge 200 -and $pixel.G -le 80 -and $pixel.B -le 80) {
                $advance = $x - 4
                break
            }
        }
        if ($advance -lt 0 -or $advance -gt 79) {
            throw ("Advance marker missing for profile {0}, U+{1:X4}." -f
                   $profile.Name, $cp)
        }

        $minX = 80; $minY = 80; $maxX = -1; $maxY = -1
        for ($y = 1; $y -lt 80; $y++) {
            for ($x = 0; $x -lt 80; $x++) {
                $pixel = $atlas.GetPixel($cellX + $x, $cellY + $y)
                if (($pixel.R + $pixel.G + $pixel.B) -ge 384) {
                    if ($x -lt $minX) { $minX = $x }
                    if ($x -gt $maxX) { $maxX = $x }
                    if ($y -lt $minY) { $minY = $y }
                    if ($y -gt $maxY) { $maxY = $y }
                }
            }
        }

        $offset = $bitmapBytes.Count
        if ($maxX -ge $minX -and $maxY -ge $minY) {
            $width = $maxX - $minX + 1
            $height = $maxY - $minY + 1
            $stride = [math]::Floor(($width + 7) / 8)
            for ($y = $minY; $y -le $maxY; $y++) {
                for ($byteIndex = 0; $byteIndex -lt $stride; $byteIndex++) {
                    $value = 0
                    for ($bit = 0; $bit -lt 8; $bit++) {
                        $sourceX = $minX + ($byteIndex * 8) + $bit
                        if ($sourceX -le $maxX) {
                            $pixel = $atlas.GetPixel($cellX + $sourceX,
                                                    $cellY + $y)
                            if (($pixel.R + $pixel.G + $pixel.B) -ge 384) {
                                $value = $value -bor (0x80 -shr $bit)
                            }
                        }
                    }
                    $bitmapBytes.Add([byte]$value)
                }
            }
            $xOffset = $minX - 4
            $yOffset = $minY - (68 - $profile.Size)
        } else {
            $width = 0
            $height = 0
            $xOffset = 0
            $yOffset = 0
        }
        $glyphRows.Add(
            ("    {{ 0x{0:X4}u, {1}u, {2}u, {3}u, {4}, {5}, {6}u }}," -f
             $cp,$offset,$width,$height,$xOffset,$yOffset,$advance))
    }

    $name = $profile.Name.ToLower()
    $sourceLines += "static const uint8_t ${name}_bitmap[] = {"
    for ($index = 0; $index -lt $bitmapBytes.Count; $index += 12) {
        $end = [math]::Min($index + 11, $bitmapBytes.Count - 1)
        $row = for ($byteIndex = $index; $byteIndex -le $end; $byteIndex++) {
            "0x{0:X2}u" -f $bitmapBytes[$byteIndex]
        }
        $sourceLines += "    $($row -join ', '),"
    }
    if ($bitmapBytes.Count -eq 0) { $sourceLines += "    0x00u," }
    $sourceLines += "};"
    $sourceLines += "static const strict_glyph_t ${name}_glyphs[] = {"
    $sourceLines += $glyphRows
    $sourceLines += "};"
    $sourceLines += ""
    $lineHeight = [math]::Ceiling($profile.Size * 1.18)
    $fontTableRows.Add(
        "    { ${name}_glyphs, ${name}_bitmap, " +
        "(uint16_t)(sizeof(${name}_glyphs) / sizeof(${name}_glyphs[0])), " +
        "${lineHeight}u },")
    $totalBytes += $bitmapBytes.Count
}

$sourceLines += @(
    "static const strict_font_t fonts[] = {"
)
$sourceLines += $fontTableRows
$sourceLines += @(
    "};",
    "",
    "static uint32_t next_codepoint(const char **text)",
    "{",
    "    const uint8_t *input = (const uint8_t *)*text;",
    "    uint32_t codepoint;",
    "    if (input[0] < 0x80u) {",
    "        codepoint = input[0];",
    "        *text += 1;",
    "    } else if ((input[0] & 0xE0u) == 0xC0u &&",
    "               (input[1] & 0xC0u) == 0x80u) {",
    "        codepoint = ((uint32_t)(input[0] & 0x1Fu) << 6) |",
    "                    (uint32_t)(input[1] & 0x3Fu);",
    "        *text += 2;",
    "    } else if ((input[0] & 0xF0u) == 0xE0u &&",
    "               (input[1] & 0xC0u) == 0x80u &&",
    "               (input[2] & 0xC0u) == 0x80u) {",
    "        codepoint = ((uint32_t)(input[0] & 0x0Fu) << 12) |",
    "                    ((uint32_t)(input[1] & 0x3Fu) << 6) |",
    "                    (uint32_t)(input[2] & 0x3Fu);",
    "        *text += 3;",
    "    } else {",
    "        codepoint = '?';",
    "        *text += 1;",
    "    }",
    "    return codepoint;",
    "}",
    "",
    "static const strict_glyph_t *find_glyph(const strict_font_t *font,",
    "                                        uint32_t codepoint)",
    "{",
    "    uint16_t low = 0u;",
    "    uint16_t high = font->glyph_count;",
    "    while (low < high) {",
    "        uint16_t middle = (uint16_t)(low + ((high - low) / 2u));",
    "        uint32_t candidate = font->glyphs[middle].codepoint;",
    "        if (candidate < codepoint) { low = (uint16_t)(middle + 1u); }",
    "        else { high = middle; }",
    "    }",
    "    if (low < font->glyph_count &&",
    "        font->glyphs[low].codepoint == codepoint) {",
    "        return &font->glyphs[low];",
    "    }",
    "    return NULL;",
    "}",
    "",
    "static const strict_font_t *get_font(watch_strict_text_style_t style)",
    "{",
    "    if ((uint32_t)style >= (sizeof(fonts) / sizeof(fonts[0]))) {",
    "        style = WATCH_STRICT_TEXT_BODY;",
    "    }",
    "    return &fonts[(uint32_t)style];",
    "}",
    "",
    "void watch_strict_draw_text(gno_context_t *graphics, int x, int y,",
    "                            const char *text,",
    "                            watch_strict_text_style_t style,",
    "                            gno_color_t color)",
    "{",
    "    if (graphics == NULL || text == NULL) { return; }",
    "    const strict_font_t *font = get_font(style);",
    "    int pen_x = x;",
    "    while (*text != '\0') {",
    "        const strict_glyph_t *glyph = find_glyph(font,",
    "                                                   next_codepoint(&text));",
    "        if (glyph == NULL) { continue; }",
    "        if (glyph->width != 0u && glyph->height != 0u) {",
    "            const gno_mono_bitmap_t bitmap = {",
    "                .width = glyph->width,",
    "                .height = glyph->height,",
    "                .row_stride_bytes =",
    "                    (uint16_t)((glyph->width + 7u) / 8u),",
    "                .pixels = font->bitmap + glyph->bitmap_offset",
    "            };",
    "            gno_draw_mono_bitmap(graphics,",
    "                                 pen_x + glyph->x_offset,",
    "                                 y + glyph->y_offset,",
    "                                 &bitmap, color, GNO_RGB(0, 0, 0), false);",
    "        }",
    "        pen_x += glyph->advance;",
    "    }",
    "}",
    "",
    "int watch_strict_text_width(const char *text,",
    "                            watch_strict_text_style_t style)",
    "{",
    "    if (text == NULL) { return 0; }",
    "    const strict_font_t *font = get_font(style);",
    "    int width = 0;",
    "    while (*text != '\0') {",
    "        const strict_glyph_t *glyph = find_glyph(font,",
    "                                                   next_codepoint(&text));",
    "        if (glyph != NULL) { width += glyph->advance; }",
    "    }",
    "    return width;",
    "}",
    "",
    "uint8_t watch_strict_text_line_height(watch_strict_text_style_t style)",
    "{",
    "    return get_font(style)->line_height;",
    "}",
    "",
    "static void strict_mask_set(uint8_t *bits, uint32_t index)",
    "{",
    "    bits[index >> 3u] |= (uint8_t)(1u << (index & 7u));",
    "}",
    "",
    "static bool watch_strict_rasterize_mask_impl(uint8_t *bits, size_t bits_size,",
    "                                              uint16_t width, uint16_t height,",
    "                                              int x, int y, const char *text,",
    "                                              watch_strict_text_style_t style, bool clear)",
    "{",
    "    size_t required = ((size_t)width * height + 7u) / 8u;",
    "    if ((bits == NULL) || (text == NULL) || (bits_size < required)) return false;",
    "    if (clear) for (size_t i = 0u; i < required; ++i) bits[i] = 0u;",
    "    const strict_font_t *font = get_font(style);",
    "    int pen_x = x;",
    "    while (*text != '\0') {",
    "        const strict_glyph_t *glyph = find_glyph(font, next_codepoint(&text));",
    "        if (glyph == NULL) continue;",
    "        for (uint8_t row = 0u; row < glyph->height; ++row) {",
    "            int target_y = y + glyph->y_offset + row;",
    "            if ((target_y < 0) || (target_y >= height)) continue;",
    "            const uint8_t *source = font->bitmap + glyph->bitmap_offset +",
    "                ((size_t)row * ((glyph->width + 7u) / 8u));",
    "            for (uint8_t column = 0u; column < glyph->width; ++column) {",
    "                if ((source[column >> 3u] & (uint8_t)(0x80u >> (column & 7u))) == 0u) continue;",
    "                int target_x = pen_x + glyph->x_offset + column;",
    "                if ((target_x >= 0) && (target_x < width))",
    "                    strict_mask_set(bits, (uint32_t)target_y * width + (uint32_t)target_x);",
    "            }",
    "        }",
    "        pen_x += glyph->advance;",
    "    }",
    "    return true;",
    "}",
    "",
    "bool watch_strict_rasterize_mask(uint8_t *bits, size_t bits_size,",
    "                                 uint16_t width, uint16_t height,",
    "                                 int x, int y, const char *text, watch_strict_text_style_t style)",
    "{",
    "    return watch_strict_rasterize_mask_impl(bits, bits_size, width, height, x, y, text, style, true);",
    "}",
    "",
    "bool watch_strict_rasterize_mask_add(uint8_t *bits, size_t bits_size,",
    "                                     uint16_t width, uint16_t height,",
    "                                     int x, int y, const char *text, watch_strict_text_style_t style)",
    "{",
    "    return watch_strict_rasterize_mask_impl(bits, bits_size, width, height, x, y, text, style, false);",
    "}"
)

$atlas.Dispose()
$headerPath = Join-Path $projectRoot "include/watch/strict_context_text.h"
$sourcePath = Join-Path $projectRoot "src/gui/strict_context_text.c"
Set-Content -LiteralPath $headerPath -Value $header -Encoding ASCII
Set-Content -LiteralPath $sourcePath -Value $sourceLines -Encoding ASCII
Write-Host ("Generated 8 Roboto mono profiles: {0} bitmap bytes." -f $totalBytes)
