set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARM_GCC_ROOT)

if(NOT DEFINED ARM_GCC_ROOT)
    message(FATAL_ERROR "ARM_GCC_ROOT is not set; run scripts/build.ps1")
endif()

file(TO_CMAKE_PATH "${ARM_GCC_ROOT}" ARM_GCC_ROOT_CMAKE)
set(TOOL_PREFIX "${ARM_GCC_ROOT_CMAKE}/bin/arm-none-eabi-")

set(CMAKE_C_COMPILER "${TOOL_PREFIX}gcc.exe")
set(CMAKE_ASM_COMPILER "${TOOL_PREFIX}gcc.exe")
set(CMAKE_OBJCOPY "${TOOL_PREFIX}objcopy.exe")
set(CMAKE_SIZE "${TOOL_PREFIX}size.exe")
